### PR TITLE
update broadcast config

### PR DESCRIPTION
**Pull request by bysomeone**
调整bityuan-fullnode.toml广播配置, 并统一放在 bityuan.go文件中, 主要是方便和bityuan.toml配置保持一致

### CODE REVIEW

**Comment by baramguli** [comment]
What is max supply of bityuan?

**Comment by bysomeone** [comment]
> What is max supply of bityuan?

current supply approximates 0.5 billion

**Comment by baramguli** [comment]
Thanks for information, but still unknown das has bityuan max supply or bityuan is inflationary coin.
For example: 
Solana total supply:  512 822 413 and circulation supply 311,207,034

Polkadot don't have max supply and it's inflationary, approximately 10% annually.
Such exact information cannot be found about bty. I invested anyway in bityuan 🚀 🙂

**Comment by bysomeone** [comment]
> 

Sorry for late reply

Bityuan supply also have no upper limit，every block issue 8 bityuan and  with consumption mechanism for transaction fee，the current annually inflation is about 10%

Github is mainly for technical issues， you can try follow ways to get more information about bityuan
Official website： https://www.bityuan.com/
Telegram： https://t.me/bityuanblockchain

**Comment by bysomeone** [comment]
> Thanks for information, but still unknown das has bityuan max supply or bityuan is inflationary coin. For example: Solana total supply: 512 822 413 and circulation supply 311,207,034
> 
> Polkadot don't have max supply and it's inflationary, approximately 10% annually. Such exact information cannot be found about bty. I invested anyway in bityuan 🚀 🙂

Sorry for late reply

Bityuan supply also have no upper limit，every block issue 8 bityuan and with consumption mechanism for transaction fee，the current annually inflation is about 10%

Github is mainly for technical issues， you can try follow ways to get more information about bityuan
Official website： https://www.bityuan.com/
Telegram： https://t.me/bityuanblockchain

**Pull request merged**
